### PR TITLE
Add GitLab handler

### LINKED ISSUE #278: Add gitlab as a repo option
See https://pypi.python.org/pypi/pyapi-gitlab/6.2.3

### PR DESCRIPTION
**Pull request by snmishra**
Would fix #278

### CODE REVIEW

**Comment by jefftriplett** [comment]
@snmishra thank you for this contribution. I'll test it and merge it after I have a chance to try it out. 

I resolved the merge conflict against master, but what it really needs is adding `python-gitlab` to our requirements.in (which I'm not sure I can do from your pull request.)

**Comment by snmishra** [comment]
> I resolved the merge conflict against master, but what it really needs is adding `python-gitlab` to our requirements.in (which I'm not sure I can do from your pull request.)

@jefftriplett Thanks for jumping on this. Done.

**Comment by jefftriplett** [comment]
🎉  @snmishra thank you for the contribution. I still have a bit of work to do before this is life (GITLAB_TOKEN key and probably putting it in a feature flag.)

**Comment by snmishra** [comment]
Hey @jefftriplett, thanks for merging this. I was able to get the Gitlab integration to work without a token. A token can get access to private repositories (and may get higher rate limits, though I don't see that in the docs). Feature flag definitely makes sense.

**Pull request merged**
