### PR TITLE
Grid with python3 supported packages only

### PR DESCRIPTION
**Pull request by rationalbeing**
Resolved Issue #448 - Filtered Python 3 supported packages in grid

### CODE REVIEW

**Comment by vaibhav-jain** [comment]
@rationalbeing Could you add testing steps as well?  they will be highly useful for historical purposes

**Comment by vaibhav-jain** [comment]
@rationalbeing Could you add screenshots of the UI before and after this PR how it is affecting?

**Comment by jefftriplett** [comment]
One thing to note is that we don't have a universally reliable way of telling that an App is using Python3 if it's not in PyPi. Check out #507 for an overview of this. We need to roll out a model change to allow us to overwrite it.

**Comment by jefftriplett** [comment]
We now have updated classifier support in #683 which gets us one more PR closer to having slightly more accurate data to judge this by. For categories of projects which might not be in pypi, I think we still need a fix to avoid accidental removal.

**Comment by jefftriplett** [comment]
This PR is depreciated by #700 and #702 

@rationalbeing thank you for your contribution. I'm closing this out because we need to do a little more work both in #702 and accounting for framework projects that aren't in pypi that are still py3 compatible. Instead of filtering out py3 projects, we are now penalizing more heavily than we were before #700

**Pull request closed without merging**
