### PR TITLE
:bug: fixes mising template

### PR DESCRIPTION
**Pull request by ryancheley**
References #1021 

I believe the issue is being caused by a missing template `templates/bootstrap3/uni_form.html`

I'm not sure if this is the best way to resolve the issue though

### CODE REVIEW

**Comment by saadmk11** [comment]
Looks like we [recently](https://github.com/djangopackages/djangopackages/commit/3de73b09f1442d93fb121ea478b06f48164a7de7) updated `django-crispy-forms` package from `1.14.0`  to `2.0`. According to the [change-log](https://github.com/django-crispy-forms/django-crispy-forms/releases/tag/2.0) there have been some major breaking changes between these versions. 

The biggest change was moving all Bootstrap template packs from `django-crispy-forms` to standalone packages and I think this change is causing the bug. We need to install [crispy-bootstrap3](https://github.com/django-crispy-forms/crispy-bootstrap3) for `django-crispy-forms` to work properly.

### This diff solved the issue for me:

```diff
diff --git a/requirements.in b/requirements.in
index a17fb2cb..9adba3bf 100644
--- a/requirements.in
+++ b/requirements.in
@@ -1,5 +1,6 @@
 bs4
 cloudflare
+crispy-bootstrap3
 croniter
 Django<5.0
 django-anymail
diff --git a/requirements.txt b/requirements.txt
index 7c93925c..6a87c26d 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -368,6 +368,10 @@ coverage[toml]==7.2.7 \
     --hash=sha256:f75f7168ab25dd93110c8a8117a22450c19976afbc44234cbf71481094c1b850 \
     --hash=sha256:fdec9e8cbf13a5bf63290fc6013d216a4c7232efb51548594ca3631a7f13c3a3
     # via pytest-cov
+crispy-bootstrap3==2022.1 \
+    --hash=sha256:be4908ca997e6ee86cda128c631b3adb33f1db483fd97fa72ae45ca3ad49ad02 \
+    --hash=sha256:f62729ed06976caf7fd5fd4fe009c0a702b0705db7765c2b486ba96c64341146
+    # via -r requirements.in
 croniter==1.4.1 \
     --hash=sha256:1a6df60eacec3b7a0aa52a8f2ef251ae3dd2a7c7c8b9874e73e791636d55a361 \
     --hash=sha256:9595da48af37ea06ec3a9f899738f1b2c1c13da3c38cea606ef7cd03ea421128
@@ -423,6 +427,7 @@ django==4.2.5 \
     --hash=sha256:b6b2b5cae821077f137dc4dade696a1c2aa292f892eca28fa8d7bfdf2608ddd4
     # via
     #   -r requirements.in
+    #   crispy-bootstrap3
     #   django-anymail
     #   django-crispy-forms
     #   django-debug-toolbar
@@ -453,7 +458,9 @@ django-click==2.3.0 \
 django-crispy-forms==2.0 \
     --hash=sha256:90193b068bf948d9c68449bc8260afed1a8e2afe11ee0bac8c4ebfaeb175b322 \
     --hash=sha256:d1d4e585929058a9ab3b797666ea5b69320b9ba7937f9d146d32173246a6fd13
-    # via -r requirements.in
+    # via
+    #   -r requirements.in
+    #   crispy-bootstrap3
 django-debug-toolbar==4.2.0 \
     --hash=sha256:af99128c06e8e794479e65ab62cc6c7d1e74e1c19beb44dcbf9bad7a9c017327 \
     --hash=sha256:bc7fdaafafcdedefcc67a4a5ad9dac96efd6e41db15bc74d402a54a2ba4854dc
diff --git a/settings/base.py b/settings/base.py
index 5ad02963..1821d05b 100644
--- a/settings/base.py
+++ b/settings/base.py
@@ -154,6 +154,7 @@ PREREQ_APPS = [
     # external
     "maintenance_mode",
     "crispy_forms",
+    "crispy_bootstrap3",
     "django_better_admin_arrayfield",
     "django_extensions",
     "django_htmx",
@@ -335,6 +336,7 @@ URL_REGEX_GITHUB = r"(?:http|https|git)://github.com/[^/]*/([^/]*)/{0,1}"
 
 ########### crispy_forms setup
 CRISPY_TEMPLATE_PACK = "bootstrap3"
+CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap3"
 ########### end crispy_forms setup
 
 ########### SEKURITY

```

**Comment by ryancheley** [comment]
Thanks @saadmk11 ! I’ll make an update and push it up

**Comment by jefftriplett** [comment]
Thank you both for jumping in on this @ryancheley @saadmk11 and sorry I wasn't around to see the breakage. I just deployed a fix that was one part this pr with a few settings changes to go along with it. 

From my other comment on the pr: 

> Our/my bus factor finally kicked in without Sentry messages making it to me. I was down with the flu for four days and then was mostly offline with my youngest having a minor procedure and came back to seeing an update broke something.

> We can re-assess and figure out how to make it easier to see these and fix them so it's not just deployed from my machine.

So le sigh. Happy to put other people in sentry, but I also need to finish automating the deploy so GH can see it.

**Comment by saadmk11** [comment]
> Thank you both for jumping in on this @ryancheley @saadmk11 and sorry I wasn't around to see the breakage. I just deployed a fix that was one part this pr with a few settings changes to go along with it.
> 
> From my other comment on the pr:
> 
> > Our/my bus factor finally kicked in without Sentry messages making it to me. I was down with the flu for four days and then was mostly offline with my youngest having a minor procedure and came back to seeing an update broke something.
> 
> > We can re-assess and figure out how to make it easier to see these and fix them so it's not just deployed from my machine.
> 
> So le sigh. Happy to put other people in sentry, but I also need to finish automating the deploy so GH can see it.

That's a good idea. We can also try out [Sentry Comments on Suspect Pull Requests](https://docs.sentry.io/product/integrations/source-code-mgmt/github/#get-sentry-comments-on-suspect-pull-requests)

**Pull request closed without merging**
