### PR TITLE
Add Sidebar and Logo for Documentation Page

### PR DESCRIPTION
**Pull request by saadmk11**
## Details
- Adds Logo to Documentation
- Adds Sidebar to Documetation
- Fixes Bullet List Warning (`Bullet list ends without a blank line`)
- Removes nonexistent references from `toctree` (`toctree contains reference to nonexisting document`)
- Fixes `:doc:` reference issue. (`unknown document: 'installation'`)

### Before:
Before

### After:
After

### CODE REVIEW

**Comment by saadmk11** [comment]
I think we should enable [Read the Docs PR Preview](https://docs.readthedocs.io/en/stable/pull-requests.html). C.C: @jefftriplett

**Comment by ryancheley** [comment]
@saadmk11  this looks like a really good idea! Do you have any input/advice on the [Privacy levels](https://docs.readthedocs.io/en/stable/pull-requests.html#privacy-levels) that should be enabled. By default the docs say they’re private. Is that a good way to do it, or does it not really matter?

**Comment by saadmk11** [comment]
> @saadmk11  this looks like a really good idea! Do you have any input/advice on the [Privacy levels](https://docs.readthedocs.io/en/stable/pull-requests.html#privacy-levels) that should be enabled. By default the docs say they’re private. Is that a good way to do it, or does it not really matter? 

I think privacy level feature is only supported on Read the Docs Business. So, for this project it should be public by default.

**Comment by jefftriplett** [comment]
@saadmk11 great suggestion. Docs PR Review should be re-enabled now.

**Comment by saadmk11** [comment]
Awesome thanks! 🎉

PR Preview:  https://djangopackages--874.org.readthedocs.build/en/874/

**Review by jefftriplett — APPROVED** [review]

**Pull request merged**
