### PR TITLE
Add changelog pre-footer link

### PR DESCRIPTION
**Pull request by vcruces**
[Issue #1169](https://github.com/djangopackages/djangopackages/issues/1169)

### CODE REVIEW

**Review by jefftriplett — APPROVED** [review]
🎉  Looks good!

**Comment by jefftriplett** [comment]
Fixes #1169

**Comment by jefftriplett** [comment]
@vcruces this looks good. Great job. I would merge it, but it's marked as a draft. Did you have any questions or is it ready to merge?

**Comment by vcruces** [comment]
> @vcruces this looks good. Great job. I would merge it, but it's marked as a draft. Did you have any questions or is it ready to merge?

Thanks Jeff! I didn't find the translations, are they added?

**Comment by jefftriplett** [comment]
@vcruces to my knowledge, they aren't enabled for the website. If you have experience with it, we can do a follow up issue to see what the lift might be to get them working?

**Comment by vcruces** [comment]
> @vcruces to my knowledge, they aren't enabled for the website. If you have experience with it, we can do a follow up issue to see what the lift might be to get them working?

Sounds good to me!

**Pull request merged**
