### PR TITLE
Doc refactor 855

### PR DESCRIPTION
**Pull request by ryancheley**

### CODE REVIEW

**Comment by ryancheley** [comment]
Initial draft for #857

**Comment by jefftriplett** [comment]
Nice work. I'll pull and check it out later. Have any opinions about sphinx vs. MkDocs? I noticed that RTD supported both last night when I was unbreaking our doc builds.

**Comment by ryancheley** [comment]
MkDocs looks interesting. And if it’s means we get to write the docs in Markdown instead of reStructuredText I’d be all for it 😁

**Review by jefftriplett — APPROVED** [review]

**Comment by jefftriplett** [comment]
@ryancheley good work. I loosely looked (on a laptop vs. bigger screen) but I think every small change is a big win.

**Pull request merged**
